variables:
  BASE: cokoapps/base
  CYPRESS: cokoapps/cypress

stages:
  - Build
  - Test

build base 18:
  stage: Build
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:27-dind
  services:
    - docker:27-dind
  only:
    - main
  before_script:
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
  script:
    - docker build
      --tag $BASE:18
      --tag $BASE:18-latest
      --tag $BASE:18-$(date +'%Y-%m-%d')
      -f Dockerfile-base-18 .
    - docker push $BASE:18
    - docker push $BASE:18-latest
    - docker push $BASE:18-$(date +'%Y-%m-%d')

build cypress 18:
  stage: Build
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:27-dind
  services:
    - docker:27-dind
  only:
    - main
  before_script:
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
  script:
    - docker build
      --tag $CYPRESS:18
      --tag $CYPRESS:18-latest
      --tag $CYPRESS:18-$(date +'%Y-%m-%d')
      -f Dockerfile-cypress-18 .
    - docker push $CYPRESS:18
    - docker push $CYPRESS:18-latest
    - docker push $CYPRESS:18-$(date +'%Y-%m-%d')

test cypress image:
  stage: Test
  needs:
    - build cypress 18
  image: $CYPRESS:18-latest
  services:
    - docker:27-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - node -v
    - cypress -v
    - docker info
    - docker compose --help
