variables:
  BASE: cokoapps/base
  DEV: cokoapps/base-dev
  DOCKER: cokoapps/base-docker
  CYPRESS: cokoapps/cypress
  RELEASE: cokoapps/release
  RELEASE_DOCKER: cokoapps/release-docker
  FLY: cokoapps/fly

stages:
  - Build
  - Test

build base 18:
  stage: Build
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:27-dind
  services:
    - docker:27-dind
  only:
    - main
  before_script:
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
  script:
    - docker build
      --tag $BASE:18
      --tag $BASE:18-latest
      --tag $BASE:18-$(date +'%Y-%m-%d')
      -f Dockerfile-base-18 .
    - docker push $BASE:18
    - docker push $BASE:18-latest
    - docker push $BASE:18-$(date +'%Y-%m-%d')

build base 20:
  stage: Build
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:27-dind
  services:
    - docker:27-dind
  only:
    - main
  before_script:
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
  script:
    - docker build
      --tag $BASE:20
      --tag $BASE:20-latest
      --tag $BASE:20-$(date +'%Y-%m-%d')
      -f Dockerfile-base-20 .
    - docker push $BASE:20
    - docker push $BASE:20-latest
    - docker push $BASE:20-$(date +'%Y-%m-%d')

build base dev 18:
  stage: Build
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:27-dind
  services:
    - docker:27-dind
  needs:
    - build base 18
  only:
    - main
  before_script:
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
  script:
    - docker build
      --tag $DEV:18
      --tag $DEV:18-latest
      --tag $DEV:18-$(date +'%Y-%m-%d')
      -f Dockerfile-base-18-dev .
    - docker push $DEV:18
    - docker push $DEV:18-latest
    - docker push $DEV:18-$(date +'%Y-%m-%d')

build base dev 20:
  stage: Build
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:27-dind
  services:
    - docker:27-dind
  needs:
    - build base 20
  only:
    - main
  before_script:
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
  script:
    - docker build
      --tag $DEV:20
      --tag $DEV:20-latest
      --tag $DEV:20-$(date +'%Y-%m-%d')
      -f Dockerfile-base-20-dev .
    - docker push $DEV:20
    - docker push $DEV:20-latest
    - docker push $DEV:20-$(date +'%Y-%m-%d')

build base docker 18:
  stage: Build
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:27-dind
  services:
    - docker:27-dind
  needs:
    - build base 18
  only:
    - main
  before_script:
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
  script:
    - docker build
      --tag $DOCKER:18
      --tag $DOCKER:18-latest
      --tag $DOCKER:18-$(date +'%Y-%m-%d')
      -f Dockerfile-base-18-with-docker .
    - docker push $DOCKER:18
    - docker push $DOCKER:18-latest
    - docker push $DOCKER:18-$(date +'%Y-%m-%d')

build base docker 20:
  stage: Build
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:27-dind
  services:
    - docker:27-dind
  needs:
    - build base 20
  only:
    - main
  before_script:
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
  script:
    - docker build
      --tag $DOCKER:20
      --tag $DOCKER:20-latest
      --tag $DOCKER:20-$(date +'%Y-%m-%d')
      -f Dockerfile-base-20-with-docker .
    - docker push $DOCKER:20
    - docker push $DOCKER:20-latest
    - docker push $DOCKER:20-$(date +'%Y-%m-%d')

build cypress 18:
  stage: Build
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:27-dind
  services:
    - docker:27-dind
  only:
    - main
  before_script:
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
  script:
    - docker build
      --tag $CYPRESS:18
      --tag $CYPRESS:18-latest
      --tag $CYPRESS:18-$(date +'%Y-%m-%d')
      -f Dockerfile-cypress-18 .
    - docker push $CYPRESS:18
    - docker push $CYPRESS:18-latest
    - docker push $CYPRESS:18-$(date +'%Y-%m-%d')

build cypress 20:
  stage: Build
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:27-dind
  services:
    - docker:27-dind
  only:
    - main
  before_script:
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
  script:
    - docker build
      --tag $CYPRESS:20
      --tag $CYPRESS:20-latest
      --tag $CYPRESS:20-$(date +'%Y-%m-%d')
      -f Dockerfile-cypress-20 .
    - docker push $CYPRESS:20
    - docker push $CYPRESS:20-latest
    - docker push $CYPRESS:20-$(date +'%Y-%m-%d')

build release 20:
  stage: Build
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:27-dind
  services:
    - docker:27-dind
  needs:
    - build base 20
  only:
    - main
  before_script:
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
  script:
    - docker build
      --tag $RELEASE:20
      --tag $RELEASE:20-latest
      --tag $RELEASE:20-$(date +'%Y-%m-%d')
      -f Dockerfile-release-20 .
    - docker push $RELEASE:20
    - docker push $RELEASE:20-latest
    - docker push $RELEASE:20-$(date +'%Y-%m-%d')

build release docker 20:
  stage: Build
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:27-dind
  services:
    - docker:27-dind
  needs:
    - build base docker 20
  only:
    - main
  before_script:
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
  script:
    - docker build
      --tag $RELEASE_DOCKER:20
      --tag $RELEASE_DOCKER:20-latest
      --tag $RELEASE_DOCKER:20-$(date +'%Y-%m-%d')
      -f Dockerfile-release-20-docker .
    - docker push $RELEASE_DOCKER:20
    - docker push $RELEASE_DOCKER:20-latest
    - docker push $RELEASE_DOCKER:20-$(date +'%Y-%m-%d')

build fly:
  stage: Build
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:27-dind
  services:
    - docker:27-dind
  only:
    - main
  before_script:
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
  script:
    - docker build --tag $FLY:latest --tag $FLY:$(date +'%Y-%m-%d') -f Dockerfile-fly .
    - docker push $FLY

test cypress image:
  stage: Test
  needs:
    - build cypress 18
  image: $CYPRESS:18-latest
  only:
    - main
  services:
    - docker:27-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - node -v
    - cypress -v
    - docker info
    - docker compose --help
