FROM alpine:3.20

RUN apk add --no-cache \
    curl \
    bash \
    git \
    ca-certificates

RUN curl -L https://fly.io/install.sh | sh
ENV PATH="/root/.fly/bin:${PATH}"
RUN flyctl version
