# Node & Semantic release

FROM cokoapps/base:20

# Install semantic release
RUN npm install --global \
    semantic-release \
    @semantic-release/changelog \
    @semantic-release/exec \
    @semantic-release/git \
    @semantic-release/gitlab
