FROM node:24-bookworm-slim

RUN apt-get update
RUN apt-get install -y python3 make g++ git imagemagick potrace ghostscript

RUN sed -i.bak 's/rights="none" pattern="PS"/rights="read | write" pattern="PS"/g' /etc/ImageMagick-6/policy.xml
RUN sed -i.bak 's/rights="none" pattern="EPS"/rights="read | write" pattern="EPS"/g' /etc/ImageMagick-6/policy.xml

RUN corepack enable
